name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Backend
        run: |
          for i in 1 2 3
          do
            echo "Attempt $i: Pinging server..."
            curl -m 20 --retry 3 --retry-delay 5 https://bnest-backend-oz7c.onrender.com/health && break
            echo "Retrying..."
            sleep 10
          done
